# -*- coding: utf-8 -*-
"""S12wccic_PySQL_HalimaAlausa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkYmuzpXJwZHQbrl0hvy4v7VS5hnQw1B

# S12 Workshop SQL
<!-- K.Schmitz (c) 2026
<!-- S09.v2.0.0
<!--
<!--   -->
"""

# @title Run this cell to mount your Google Drive
#
# This setup information must remain unmodified
# The first code will mount your Google Drive and make its contents accessible to the Colaboratory
from google.colab import drive
drive.mount('/content/drive', force_remount=False)
#
# Add the CIS2010 folder to the path to other scripts and files can be found
import os
os.chdir('/content/drive/My Drive/CIS2010')
#
# Load in supporting functions
from cis2010utils6 import StartHere, EndHere, strhash, hecho, runsql
import pandas as pd
import sqlite3

"""#StartHere
StartHere() is a function that needs three arguments. Enter your name as the first argument, then click the Run Code button (circle with triangle).
"""

# Task 2a Add your name in quotes for the first argument
StartHere("Halima Alausa", "S12w", "S12.2.0.0")

# Open up the database  ########## Do not modify these instructions#########
db_name =  "Movies2023x4.db"
db_conn = sqlite3.connect(db_name)
sqltxt = "pragma table_info('movies')" ; t1 = pd.read_sql(sqltxt, db_conn) ; print("movies table\n", t1)
sqltxt = "pragma table_info('crew')" ; t2 = pd.read_sql(sqltxt, db_conn) ; print("crew table\n", t2)
sqltxt = "pragma table_info('lang')" ; t3 = pd.read_sql(sqltxt, db_conn) ; print("lang table\n", t3)
sqltxt = "pragma table_info('genre')" ; t4 = pd.read_sql(sqltxt, db_conn) ; print("genre table\n", t4)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

# Task w3a
sqlw3a = """
SELECT year FROM movies
"""
w3a = runsql( sqlw3a, db_conn, False, "task w3a")

# Task w3c
sqlw3c = """
SELECT DISTINCT year FROM movies
"""
w3c = runsql( sqlw3c, db_conn, False, "task w3c")

# Task w4a
sqlw4a = """
SELECT year, title, revenue
FROM movies
WHERE title = 'Barbie'
"""
w4a = runsql( sqlw4a, db_conn, True, "task w4a")

# Task w4b
sqlw4b = """
SELECT year, title, revenue
FROM movies
WHERE title LIKE '%Barbie%'
"""
w4b = runsql( sqlw4b, db_conn, True, "task w4b")

# Task w4c
sqlw4c = """
SELECT year, title, revenue
FROM movies
WHERE title LIKE '%indiana jones%'
ORDER BY revenue
"""
w4c = runsql( sqlw4c, db_conn, True, "task w4c")

# Task w5a
sqlw5a = """
SELECT year, title, actor
FROM movies
WHERE title LIKE '%indiana jones%'
"""
w5a = runsql( sqlw5a, db_conn, True, "task w5a")

# Task w5c
sqlw5c = """
SELECT*FROM crew
"""
w5c = runsql( sqlw5c, db_conn, False, "task w5c")

# Task w5d
sqlw5d = """
SELECT year, title, actor
FROM movies JOIN crew ON movies.mid = crew.movieID
WHERE title LIKE '%indiana jones%'
"""
w5d = runsql( sqlw5d, db_conn, True, "task w5d")

# Task w5e
sqlw5e = """
SELECT year, title, actor
FROM movies JOIN crew ON movies.mid = crew.movieID
WHERE title LIKE '%indiana jones%' AND actor = 'John Rhys-Davies'
"""
w5e = runsql( sqlw5e, db_conn, False, "task w5e")

# Task w6a
sqlw6a = """
SELECT year, title, actor, MAX(revenue)
FROM movies JOIN crew ON movies.mid = crew.movieID
WHERE actor = 'Zoe Saldana'
"""
w6a = runsql( sqlw6a, db_conn, True, "task w6a")

# Task w6b
sqlw6b = """
SELECT actor, SUM(revenue)
FROM movies JOIN crew ON movies.mid = crew.movieID
WHERE actor LIKE '%Zoe Saldana%'
"""
w6b = runsql( sqlw6b, db_conn, True, "task w6b")

# Task w7a
sqlw7a = """
SELECT DISTINCT genre
FROM movies JOIN genre ON movies.title = genre.title
WHERE movies.title LIKE '%Avatar%'
"""
w7a = runsql( sqlw7a, db_conn, False, "task w7a")

# Task w7b
# write a SQL command to determine the genre of movies in the Indiana Jones franchise.
sqlw7b = """
SELECT DISTINCT G.genre
FROM movies AS M
JOIN genre AS G ON M.title = G.title
WHERE M.title LIKE '%Indiana Jones%'
"""
w7b = runsql( sqlw7b, db_conn, False, "task w7b")

# Task w7c
sqlw7c = """

"""
w7c = runsql( sqlw7c, db_conn, False, "task w7c")

"""#Collaboration Challenge"""

#S09 CC Q4
pd.set_option('display.max_rows', 32)
StartHere("Halima Alausa", "S12wcc", "S12.2.0.0")

# S12ccq Q5
sqlcc5 = """
SELECT COUNT(title)
FROM movies
WHERE title LIKE 'Frozen%'
"""
cc5 = runsql( sqlcc5, db_conn, False, "task cc5")

# S12ccq Q6
sqlcc6 = """
SELECT COUNT(title)
FROM movies
WHERE title LIKE 'Frozen%' AND budget > 100000000.0
"""
cc6 = runsql( sqlcc6, db_conn, False, "task cc6")

# S12ccq Q7
sqlcc7 = """
SELECT title, actor
FROM movies JOIN crew ON movies.mid = crew.movieID
WHERE title LIKE 'Frozen%' AND actor = 'Idina Menzel'
"""
cc7 = runsql( sqlcc7, db_conn, False, "task cc7")

# S12ccq Q8
sqlcc8 = """
SELECT DISTINCT genre
FROM movies JOIN genre ON movies.title = genre.title
WHERE movies.title LIKE 'Frozen%'
"""
cc8 = runsql( sqlcc8, db_conn, False, "task cc8")

# S12ccq Q9
sqlcc9 = """
SELECT COUNT(title)
FROM movies
WHERE title LIKE '%Spider%'
"""
cc9 = runsql( sqlcc9, db_conn, False, "task cc9")

# S12ccq Q10
sqlcc10 = """
SELECT year, title, actor
FROM movies JOIN crew ON movies.mid = crew.movieID
WHERE title LIKE '%Spider-Man%' AND year = '2002'
"""
cc10 = runsql( sqlcc10, db_conn, False, "task cc10")

# S12ccq Q11
sqlcc11 = """
SELECT DISTINCT G.genre
FROM movies AS M
JOIN genre AS G on M.title = G.title
WHERE M.title LIKE '%Black Panther%' and year = 2022
"""
cc11 = runsql( sqlcc11, db_conn, False, "task cc11")

# S12ccq Q12
sqlcc12 = """
SELECT title, genre
FROM genre
WHERE title LIKE '%Shrek%' and genre = 'Science Fiction'
"""
cc12 = runsql( sqlcc12, db_conn, False, "task cc12")

# S12ccq Q13
sqlcc13 = """
SELECT year, title
FROM movies
WHERE title LIKE '%Shrek%' and year = 2010
"""
cc13 = runsql( sqlcc13, db_conn, False, "task cc13")

"""#Individual Challenge"""

# S12 IC Q1
StartHere("Halima Alausa", "S12wccic", "S12.2.0.0")

# S12icq Q2
sqlic2 = """
SELECT * FROM lang
"""
ic2 = runsql( sqlic2, db_conn, False, "task ic2")

# S12icq Q3
sqlic3 = """
SELECT title, orig_lang
FROM movies JOIN lang ON movies.mid = lang.mid
WHERE title = 'The Pope: Answers'
"""
ic3 = runsql( sqlic3, db_conn, False, "task ic3")

# S12icq Q4
sqlic4 = """
SELECT budget, score, actor, MAX(revenue)
FROM movies JOIN crew ON movies.mid = crew.movieID
WHERE actor = 'Whoopi Goldberg'
"""
ic4 = runsql( sqlic4, db_conn, False, "task ic4")

# S12icq Q5
sqlic5 = """
SELECT title, year
FROM movies
WHERE title = 'Titanic'
"""
ic5 = runsql( sqlic5, db_conn, False, "task ic5")

# S12icq Q6
sqlic6 = """
SELECT title, country
FROM movies JOIN lang ON movies.mid = lang.mid
WHERE title = 'Chevalier'
"""
ic6 = runsql( sqlic6, db_conn, False, "task ic6")

# S12icq Q7
sqlic7 = """
SELECT DISTINCT genre
FROM movies JOIN genre ON movies.title = genre.title
WHERE movies.title LIKE '%Cruella%'
"""
ic7 = runsql( sqlic7, db_conn, False, "task ic7")

# Do not modify the code in this cell. This must be the last cell of your project.
# This funcation saves your variables into a file for grading purposes.
db_conn.close()
EndHere( globals() )